export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_FAILED = "PRODUCT_FAILED";
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS";
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
